#define _GNU_SOURCE

#include <stdio.h>
#include <stdint.h>
#include <time.h>

#include<math.h>

#if defined(WITH_INLINE_FUNCTIONS)
// experimental, use inline sleef functions for avx2 or better
#include <string.h>
#include <x86intrin.h>
#define SLEEF_ALWAYS_INLINE inline
#define SLEEF_INLINE static inline
#define SLEEF_CONST const
#define INT_MIN  -2147483648
#define INT_MAX  2147483647
#define DBL_MIN  2.2250738585072014E-308
#define FLT_MIN  1.175494e-38
#include <sleefinline_avx2.h>

#else
// normal mode, use sleef from library
#include <sleef.h>

#endif

// used for X86 timing tests
#if defined(NO_X86)
#define USE_RDTSCP
#undef __x86_64__
#endif

// compile wrappers with calls to libm instead of using sleef
#if defined(NO_SLEEF)
#undef __SLEEF_H__
#endif

// code generated by FUNCTIONS.sh
#include <functions.h>
